run:
  timeout: 3m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert

issues:
  exclude-dirs:
    - vendor
