import { TCOInput } from "./tco";

export type PresetKey = "cash" | "loan" | "lease";

export const PRESETS: Record<PresetKey, TCOInput> = {
  cash: {
    vehicleName: "2024 Honda Civic",
    powertrain: "gas",
    acquisition: "cash",
    purchasePrice: 28000,
    downPayment: 28000,
    salesTaxRate: 7.5,
    loanTermMonths: 0,
    loanInterestRate: 0,
    ownershipYears: 5,
    annualMileage: 12000,
    fuelEconomyMPG: 33,
    fuelPricePerGal: 3.80,
    efficiencyKWhPer100Mi: 0,
    electricityRatePerKWh: 0,
    annualInsurance: 1400,
    annualMaintenance: 700,
    annualFees: 300,
    depreciationRate: 14.0,
  },
  loan: {
    vehicleName: "2024 Toyota RAV4 Hybrid",
    powertrain: "hybrid",
    acquisition: "loan",
    purchasePrice: 34500,
    downPayment: 6000,
    salesTaxRate: 7.5,
    loanTermMonths: 60,
    loanInterestRate: 5.5,
    ownershipYears: 5,
    annualMileage: 14000,
    fuelEconomyMPG: 39,
    fuelPricePerGal: 3.80,
    efficiencyKWhPer100Mi: 0,
    electricityRatePerKWh: 0,
    annualInsurance: 1550,
    annualMaintenance: 650,
    annualFees: 320,
    depreciationRate: 13.0,
  },
  lease: {
    vehicleName: "2024 Tesla Model 3",
    powertrain: "electric",
    acquisition: "lease",
    purchasePrice: 38990,
    downPayment: 0,
    salesTaxRate: 7.5,
    loanTermMonths: 0,
    loanInterestRate: 0,
    ownershipYears: 3,
    annualMileage: 12000,
    fuelEconomyMPG: 0,
    fuelPricePerGal: 0,
    efficiencyKWhPer100Mi: 25,
    electricityRatePerKWh: 0.16,
    annualInsurance: 1650,
    annualMaintenance: 450,
    annualFees: 350,
    depreciationRate: 15.0,
    lease: {
      leaseTermMonths: 36,
      dueAtSigning: 3500,
      monthlyPayment: 429,
      moneyFactor: 0.0022,
      residualPercent: 57.0,
      acquisitionFee: 695,
      dispositionFee: 395,
      annualMileageLimit: 12000,
      excessMileageFeeRate: 0.25,
      buyoutAtEnd: false,
    },
  },
};
